name: CheckWater

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - Utility/CheckWater/**.*
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compress
        run: zip -r CheckWater.zip Utility/CheckWater

      - name: Create / Edit Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check Water
          tag: CheckWater
          allowUpdates: true
          replacesArtifacts: true
          bodyFile: Utility/CheckWater/README.md
          artifacts: CheckWater.zip
          artifactContentType: application/zip
