name: CoinStack

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - CustomSprites/CoinStack/**.*
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compress
        run: zip -r CoinStack.zip CustomSprites/CoinStack

      - name: Create / Edit Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Coin Stack
          tag: CoinStack
          allowUpdates: true
          replacesArtifacts: true
          bodyFile: CustomSprites/CoinStack/README.md
          artifacts: CoinStack.zip
          artifactContentType: application/zip
